### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by peidong** [xuhdev/vim-latex-live-preview#10]
The plugin cannot preview the latex when it contains graphs and images. I am using Ubuntu 14.04

**Comment by xuhdev** [comment]
It should work with graphs. Can you describe your issue in more details? Does your file compile normally with pdflatex on command line?

**Comment by peidong** [comment]
It can be compiled normally when using pdflatex.
And I can use vim-preview when not including images.

This is the document I use. Could you do it?
https://www.sharelatex.com/project/554ab8a74f41f2520d548cf6

**Comment by chantisnake** [comment]
I have tried this, I think this error is caused by pdflatex.
![capture](https://cloud.githubusercontent.com/assets/10100995/13395451/cadea8b2-debc-11e5-8ddd-b492ec8b24d3.PNG)

online tex editor usually used many tex compiler to compile. I don't know what the problem is...

Also, MikTex installed many packages on the fly for me, make sure that you got all the dependency installed.

**Comment by chantisnake** [comment]
@peidong 
If you can, just run the `pdflatex <wherever the file is>` and past the error message here, that will be helpful
