### ISSUE TITLE
LLP Engine

### ISSUE THREAD

**Issue by cream68** [xuhdev/vim-latex-live-preview#38]
Im having trouble configuring 
**let g:livepreview_engine = 'your_engine' . ' [options]'**
the right way. I dont want to run pdflatex als preview engine, instead maybe dvi->ps->pdf or just dvi. What do I have to do?

**Comment by badouralix** [comment]
This plugin has not be designed to preview anything but pdf files.

Anyway, this could be a good feature. I don't use dvi or ps format files. Can you provide the tools you are using and how you want the plugin to work, so than we can implement it? Thanks

**Comment by cream68** [comment]
Hey badouralix,

i mean is it possible to select the "quickbuild" option for the preview compiling, which first compiles dvi -> ps -> pdf? thank you in advance!

**Comment by badouralix** [comment]
Okay, IIUC you'd like to compile to dvi instead of pdf and preview on the dvi directly?
Right now, it's not possible to do so because the pdf extension is actually [hardcoded in the plugin](https://github.com/xuhdev/vim-latex-live-preview/blob/2cad7426de4344428a45eba1192944c0bf9a35e6/plugin/latexlivepreview.vim#L141), but that could be a good feature to add though

**Comment by badouralix** [comment]
@ranguli what do you think about using `latexmk` instead of a hand-made combination of `pdflatex` and `bibtex`? So that choosing between div, ps or pdf will be for free

**Comment by ranguli** [comment]
@badouralix I think it's a good step for sure
